name: Codacy Coverage Reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter

    steps:
        - uses: actions/download-artifact@master
          with:
            name: clover.xml
            path: build/logs
        - shell: bash
          env:
            CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
          run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r clover.xml